{
 "title": "openuds monitor",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "pool", "label": "Pool", "query": "label_values(pool)" }
  ]
 },
 "panels": [
  {
   "title": "Usuarios",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "openuds_auth_users_total" }
   ]
  },
  {
   "title": "Grupos",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "openuds_auth_groups_total" }
   ]
  },
  {
   "title": "Cantidad pools",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "openuds_pool_total" }
   ]
  },
  {
   "title": "$pool",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 13 },
   "repeat": "pool",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "color": "red",
     "expr": "max_over_time(openuds_pool_max_srvs{pool=\"$pool\"}[$__interval])",
     "legendFormat": "max"
    },
    {
     "expr": "min_over_time(openuds_pool_userservice_cached_count{pool=\"$pool\"}[$__interval])",
     "legendFormat": "cache"
    },
    {
     "expr": "max_over_time(openuds_pool_userservice_assigned_count{pool=\"$pool\"}[$__interval])",
     "legendFormat": "asignados"
    },
    {
     "expr": "max_over_time(openuds_pool_userservice_assigned_notinuse_count{pool=\"$pool\"}[$__interval])",
     "legendFormat": "asignados no en uso"
    }
   ]
  },
  {
   "title": "Pool max config value",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max_over_time(openuds_pool_max_srvs{pool=~\".*\"}[$__interval])",
     "legendFormat": "{{pool}}"
    }
   ]
  }
 ]
}