# my global config
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape evaluates rules 15 seconds.
  # scrape_timeout # default: 10s.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'openudsmonitor'

# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'uds'
    scrape_interval: 60s
    # default timeout is 10 seg.
    scrape_timeout: 30s
    scheme: https
    metrics_path: /prom
    tls_config:
       insecure_skip_verify: true
    static_configs:
       # this is for *service*: use service url instead of hostnames
       - targets: ['vdi.domain.com:443']
    relabel_configs:
       - source_labels: [__address__]
         regex:  '(\w+)[\.]*(.*):(\d+)'
         target_label: instance
         replacement: '$1'

